import { Manrope, Covered_By_Your_Grace } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";

const manrope = Manrope({ subsets: ["latin"] });
export const covered_font = Covered_By_Your_Grace({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
